version: "3.9"
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
      - 9901:9901
    volumes:
      - ./docker/conf/envoy-final.yaml:/etc/envoy/envoy.yaml
    
