# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import western_movies_pb2 as western__movies__pb2


class WesternMoviesStub(object):
    """The western movie service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetByName = channel.unary_unary(
                '/westernmovies.WesternMovies/GetByName',
                request_serializer=western__movies__pb2.NameRequest.SerializeToString,
                response_deserializer=western__movies__pb2.MovieResponse.FromString,
                )


class WesternMoviesServicer(object):
    """The western movie service definition.
    """

    def GetByName(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WesternMoviesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByName,
                    request_deserializer=western__movies__pb2.NameRequest.FromString,
                    response_serializer=western__movies__pb2.MovieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'westernmovies.WesternMovies', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WesternMovies(object):
    """The western movie service definition.
    """

    @staticmethod
    def GetByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/westernmovies.WesternMovies/GetByName',
            western__movies__pb2.NameRequest.SerializeToString,
            western__movies__pb2.MovieResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
