# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: western_movies.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14western_movies.proto\x12\rwesternmovies\"\x1b\n\x0bNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"@\n\rMovieResponse\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\x0f\n\x07topCast\x18\x02 \x01(\t\x12\x10\n\x08overview\x18\x03 \x01(\t2X\n\rWesternMovies\x12G\n\tGetByName\x12\x1a.westernmovies.NameRequest\x1a\x1c.westernmovies.MovieResponse\"\x00\x62\x06proto3')



_NAMEREQUEST = DESCRIPTOR.message_types_by_name['NameRequest']
_MOVIERESPONSE = DESCRIPTOR.message_types_by_name['MovieResponse']
NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAMEREQUEST,
  '__module__' : 'western_movies_pb2'
  # @@protoc_insertion_point(class_scope:westernmovies.NameRequest)
  })
_sym_db.RegisterMessage(NameRequest)

MovieResponse = _reflection.GeneratedProtocolMessageType('MovieResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOVIERESPONSE,
  '__module__' : 'western_movies_pb2'
  # @@protoc_insertion_point(class_scope:westernmovies.MovieResponse)
  })
_sym_db.RegisterMessage(MovieResponse)

_WESTERNMOVIES = DESCRIPTOR.services_by_name['WesternMovies']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAMEREQUEST._serialized_start=39
  _NAMEREQUEST._serialized_end=66
  _MOVIERESPONSE._serialized_start=68
  _MOVIERESPONSE._serialized_end=132
  _WESTERNMOVIES._serialized_start=134
  _WESTERNMOVIES._serialized_end=222
# @@protoc_insertion_point(module_scope)
